# Generated by Django 3.0.5 on 2020-04-06 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.PositiveIntegerField(verbose_name='Дом')),
                ('corpus', models.CharField(max_length=50, verbose_name='Корпус')),
                ('flat', models.PositiveIntegerField(verbose_name='Квартира')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс')),
                ('name', models.CharField(max_length=100, verbose_name='Адрес фактического проживания')),
            ],
            options={
                'verbose_name': 'Адрес фактического проживания',
                'verbose_name_plural': 'Адреса фактического проживания',
            },
        ),
        migrations.CreateModel(
            name='AddressPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.PositiveIntegerField(verbose_name='Дом')),
                ('corpus', models.CharField(max_length=50, verbose_name='Корпус')),
                ('flat', models.PositiveIntegerField(verbose_name='Квартира')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс')),
                ('name', models.CharField(max_length=100, verbose_name='Почтовый адрес для связи')),
            ],
            options={
                'verbose_name': 'Почтовый адрес для связи',
                'verbose_name_plural': 'Почтовые адреса для связи',
            },
        ),
        migrations.CreateModel(
            name='AddressRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.PositiveIntegerField(verbose_name='Дом')),
                ('corpus', models.CharField(max_length=50, verbose_name='Корпус')),
                ('flat', models.PositiveIntegerField(verbose_name='Квартира')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс')),
                ('name', models.CharField(max_length=100, verbose_name='Адрес регистрации')),
            ],
            options={
                'verbose_name': 'Адрес регистрации',
                'verbose_name_plural': 'Адреса регистрации',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_user', models.CharField(max_length=50, verbose_name='Личный номер пользователя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('passport', models.CharField(max_length=15, verbose_name='Паспорт')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=25, verbose_name='Гражданство')),
                ('division_code', models.CharField(max_length=15, verbose_name='Код подразделения')),
                ('date_passport', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('inn', models.PositiveIntegerField(verbose_name='ИНН')),
                ('by_passport', models.CharField(max_length=250, verbose_name='Кем выдан')),
                ('profile_region', models.CharField(max_length=50, verbose_name='Регион')),
                ('profile_city', models.CharField(max_length=50, verbose_name='Город')),
                ('date_activation', models.DateTimeField(blank=True, help_text='Заполняется администратором', null=True, verbose_name='Дата активации')),
                ('accumulated_queue', models.PositiveIntegerField(verbose_name='Накопленно для очереди')),
                ('left_queue', models.PositiveIntegerField(verbose_name='Осталось для очереди')),
                ('documents', models.BooleanField(default=False, verbose_name='Документы да/нет')),
                ('number_queue', models.PositiveIntegerField(verbose_name='Номер очереди')),
                ('date_acquisition', models.DateField(verbose_name='Дата покупки объекта')),
                ('date_joined', models.DateTimeField(verbose_name='Дата активации')),
                ('date_repayment', models.DateTimeField(verbose_name='Дата погашения')),
                ('installment_period', models.DateTimeField(verbose_name='Срок рассрочки')),
                ('percent_installment', models.CharField(max_length=15, verbose_name='Процент рассрочки')),
                ('number_score', models.CharField(max_length=15, verbose_name='Номер счета')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
