# Generated by Django 3.0.5 on 2020-04-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200406_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressactual',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='addresspost',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Почтовый адрес для связи'),
        ),
        migrations.AlterField(
            model_name='addressregistration',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Адрес регистрации'),
        ),
    ]
