# Generated by Django 3.0.5 on 2020-04-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200406_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressactual',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Profile', verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='addresspost',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Profile', verbose_name='Почтовый адрес для связи'),
        ),
    ]
